name: math_expressions
version: 2.4.0
homepage: https://github.com/fkleon/math-expressions
description: A library for parsing and evaluating mathematical expressions, supporting real numbers, vectors, and basic interval arithmetic.

dependencies:
  vector_math: ^2.1.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.7

environment:
  sdk: '>=2.12.0 <3.0.0'
