name: math_expressions
version: 0.3.0-dev
author: Frederik Leonhardt <frederik.leonhardt@gmail.com>
description: A math library for parsing and evaluating expressions in real, interval and vector contexts. Also supports simplification and differentiation.
homepage: https://github.com/fkleon/math-expressions
documentation: http://www.dartdocs.org/documentation/math_expressions/latest
dependencies:
  vector_math: '>=2.0.0 <2.1.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
environment:
  sdk: '>=0.8.10+6 <2.0.0'
